# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-18 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nomenclature',
            options={},
        ),
    ]
